plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md

theme: jekyll-theme-cayman
title: "Introdução à Programação com JavaScript"
show_downloads: false
google_analytics: "UA-166869949-2"
